### ISSUE TITLE
Auth-Type is CHAP, passwords can be exposed in clear in freeradius logs

### ISSUE THREAD

**Issue by peppelinux** [robgolding/django-radius#13]
Hi Rob,
Is there any possibility to introduce an mschap auth type instead of a CHAP method as actually it does.
If a sysadmin configures a freeradius to log all the auth good_pass and bad_pass he could be also read all the password in clear, in /var/log/freeradius/radius.log.

The question could be also asked this way:
Can pyrad client stablish an auth session in mschap instead of chap?

**Comment by peppelinux** [comment]
The problem is pyrad implementation, not django-radius. I also asket to pyrad author in this issue, or enanchment request:

https://github.com/wichert/pyrad/issues/40

**Comment by peppelinux** [comment]
With the examples in pyprotosim I implemented a pure eapol_test python client program, downloadable here: https://github.com/peppelinux/pyEapol_test

I'll ask to pyrad author if there will be some possibility to introduce PEAP auth-type into pyrad, starting on this client or something similar. With a radius auth_backend that permits only PEAP auth-type we would be very strong on the security side.

**Comment by robgolding** [comment]
Hey @peppelinux! If you're able to get PEAP auth working with `pyrad`, then you could create a subclass of `RADIUSBackend` to use it. Unfortunately until then there's not much we can do on this end. I'm closing this issue now, but please feel free to open a PR in future once the upstream changes have been made. And thanks for the interesting in the project!
