### ISSUE TITLE
List `future` in requirements.txt

### ISSUE THREAD

**Issue by AlanCoding** [robgolding/django-radius#15]
I have been updating dependencies for the AWX project https://github.com/ansible/awx

Upgrading django-radius 1.1.0->1.3.2 caused the following type of problem due to the introduction of the import of the `future` library.

```
awx/main/tests/functional/api/test_unified_jobs_view.py:5: in <module>
    from awx.main.tests.base import URI
/venv/awx/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:171: in load_module
    py.builtin.exec_(co, mod.__dict__)
awx/main/tests/base.py:33: in <module>
    from awx.sso.backends import LDAPSettings
/venv/awx/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:171: in load_module
    py.builtin.exec_(co, mod.__dict__)
awx/sso/backends.py:23: in <module>
    from radiusauth.backends import RADIUSBackend as BaseRADIUSBackend
/venv/awx/lib/python2.7/site-packages/radiusauth/backends/__init__.py:1: in <module>
    from radiusauth.backends.radius import RADIUSBackend, RADIUSRealmBackend
/venv/awx/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:171: in load_module
    py.builtin.exec_(co, mod.__dict__)
/venv/awx/lib/python2.7/site-packages/radiusauth/backends/radius.py:1: in <module>
    from future import standard_library
E   ImportError: No module named future
```

It appears that this import refers to

https://pypi.python.org/pypi/future
http://python-future.org/quickstart.html

This is different from other future libraries (of which there are several).

If you could place that requirement inside of https://github.com/robgolding/django-radius/blob/develop/requirements.txt, then this will allow us to remove the extra pinned dependency inside of our own requirements.

Thanks.

**Comment by robgolding** [comment]
Thanks for the report! Fixed this and released version 1.3.3 to PyPI.
