### ISSUE TITLE
Django 1.11 authentication compatibility issue

### ISSUE THREAD

**Issue by ncbrown1** [robgolding/django-radius#7]
In Django 1.11, the `django.contrib.auth.authenticate` method sends the request object to the authentication backend's `authenticate()` method. In this package, there is a decorator function `utf8_encode_args` that is used on the `RADIUSBackend` class's `authenticate()` method which calls a method `encode` on all args and kwargs. Since the Django Request class has no `encode()` method, this causes a `TypeError` like below.

Further testing should be done on this problem and perhaps a fix. I solved the issue on my server by commenting out the line containing the decorator in `/usr/local/lib/python2.7/dist-packages/radiusauth/backends/radius.py` (for my version - v1.1.0, this is line 59). This is undesirable in the long run, so a more permanent fix would be well appreciated!

```
AttributeError at /login/
'WSGIRequest' object has no attribute 'encode'
Request Method: POST
Request URL:    https://localhost/login/?next=/
Django Version: 1.11.3
Exception Type: AttributeError
Exception Value:
'WSGIRequest' object has no attribute 'encode'
Exception Location:     /usr/local/lib/python2.7/dist-packages/radiusauth/backends/radius.py in encoded, line 59
Python Executable:      /usr/bin/python
Python Version: 2.7.6
Python Path:
['/home/file_xfer',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.7’]
```

**Comment by robgolding** [comment]
Released `1.3.0` which supports Django 1.11! Thanks for the detailed report.
