### ISSUE TITLE
name 'utf8_encode_args' is not defined

### ISSUE THREAD

**Issue by peppelinux** [robgolding/django-radius#9]
in radiusauth/backends/radius.py with last git version, commit #233e213

authenticate method still have @utf8_encode_args declared.
````
    @utf8_encode_args
    def authenticate(self, username, password, realm):
````

This raises an exception 'cause utf8_encode_args cannot be found.
Adding the old definition of utf8_encode_args in radius.py I got another exception:
````
secret must be a binary string
````

If I remove the utf8_encode_args decorator pyrad raises the same exception about the secret, that must be a binary string.

**Comment by peppelinux** [comment]
I patched to get it work, Pull request is also pendent in development branch.
It is not so brilliant as solution but works, it could be helpfull to understand the origin of the problem before recode the solution in a official way.

Thank you all for this beatifull auth backend

**Comment by robgolding** [comment]
Thanks for the report! Sorry about missing that in my latest update. I'll fix the Pyrad issue as well and release a new version shortly.

**Comment by peppelinux** [comment]
Still have an exception:

````
'int' object has no attribute 'encode'
````

hugly patched at line 105, from

````
 s.encode('utf-8') for s in [
````
to

````
str(s).encode('utf-8') for s in [
           
````

probably RADIUS_PORT came as INT

**Comment by robgolding** [comment]
🤦‍♂️  yes, you're right. Patch release uploaded as v1.3.2 which only encodes the secret as UTF-8.
